version: '3'

services:
  egidio-app:
    image: postgres
    restart: always
    volumes:
      - egidio:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: learning
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

volumes:
  egidio:
